### ISSUE TITLE
En Departamentos agregar nuevos campos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-human-resources#19]
Nuevos campos:
- Bodega de materia prima
- Bodega de consumibles
- Bodega de productos terminados

Tomar en cuenta:
- Ver campos en configuración inicial de compras.
- Correr nuevo archivo de migración del módulo.

**Comment by mgallegos** [comment]
Favor de reordenar campos:
- columna izquierda: Nombre, centro de costo, Bodega de productos terminados (para la venta)
- columna derecha: Bodega de consumibles, Bodega de materia prima

**Comment by alvarogarcia1010** [comment]
Listo!
