### ISSUE TITLE
Desarrollar pantalla de Gestión de Cargos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-human-resources#5]
Controlador: PositionManager.php

Repositorio: EloquentPosition.php

Servicio: PositionManager.php

Vista: position-management.blade.php

Modelo: Position.php

**Comment by mgallegos** [comment]
Controlador: PositionManager.php

Repositorio: EloquentPosition.php

Servicio: PositionManager.php

Vista: position-manager.blade.php

Modelo: Position.php

**Comment by mgallegos** [comment]
Pendientes al 02/09:
- Agregar campo money al salario
- Implementar auditoría de editar
- Al eliminar se debe mostrar el nombre del cargo en el alert y en el mensaje de exito
- Cambiar el [autocomplete del centro de costo](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Controllers/JournalManager.php#L111).

**Comment by caceres97** [comment]
Solución de Bugs :v, 
-Auditoria resulta :D
-El eliminar name falta :'v
-Currency agregado al grid

**Comment by caceres97** [comment]
Terminado ! :D

**Comment by mgallegos** [comment]
Bug - @caceres97 al guardar es necesario quitarle las comas al campo salario. Ejemplo:

https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/JournalManagement/JournalManager.php#L740
