### ISSUE TITLE
Desarrollar pantalla de Gestión de Departamentos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-human-resources#6]
Controlador: DeparmentManager.php

Repositorio: EloquentDeparment.php

Servicio: DeparmentManager.php

Vista: deparment-management.blade.php

Modelo: Deparment.php

**Comment by mgallegos** [comment]
Tareas:
- Agregar la script la columna de centro de costo (ver archivo de diseño)
- Agregar autocomplete de centro de costo ([ver ejemplo](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Controllers/CostCenterManager.php#L73))

**Comment by mgallegos** [comment]
Pendientes al 02/09:
- Cambiar el [autocomplete del centro de costo](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Controllers/JournalManager.php#L111).
- Revisar archivo de idiomas
- Implementar auditoría de centro de costo

**Comment by mgallegos** [comment]
Pendientes al 03/09:
-  Centro de costo no es obligatorio
- Revisar que funcionen las operaciones de agregar, editar y eliminar.

**Comment by mgallegos** [comment]
Ejemplo de concatenación en SQL del grid:

https://github.com/mgallegos/decima-asset/blob/master/src/Mgallegos/DecimaAsset/Asset/Repositories/Category/EloquentCategoryGridRepository.php#L41

**Comment by mgallegos** [comment]
Pendientes al 11/07 cc @caceres97 :
- Cambiar el [autocomplete del centro de costo](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Controllers/JournalManager.php#L111).
-  Implementar auditoría de centro de costo, se tienen que ver los nombres de los centros en la auditoría (para hacer la prueba, tenes que agregar un nuevo centro en la pantalla Gestión de centros de costo, esta con contabilidad -> configuracion).
- Al eliminar en el mensaje se esta mostrando mal, asó _Se eliminó el cargo ":name" seleccionado en el sistema._

**Comment by mgallegos** [comment]
[Ver ejemplo de implementación de autocomplete](https://github.com/mgallegos/decima-asset/blob/master/src/Mgallegos/DecimaAsset/Asset/Services/CategoryManagement/CategoryManager.php#L287-L300).

**Comment by mgallegos** [comment]
Incluir en el servicio el [repositorio de centro de costo](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/JournalManagement/JournalManager.php#L42).

**Comment by mgallegos** [comment]
En el ServiceProvider [agregar repositorio de centro de costo](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/DecimaAccountingServiceProvider.php#L382).

**Comment by caceres97** [comment]
Solución de Crasheos:
-Ya esta el autocomplete bueno :D
-Auditoria terminada
-Falta el de eliminar :'v

**Comment by caceres97** [comment]
Terminado  ! :D

**Comment by caceres97** [comment]
Terminado ! :D

**Comment by mgallegos** [comment]
Revisa @caceres97 este cambio que hice, era para resolver que el autocomplete no tomaba en la tamaño completo de la columna:

https://github.com/mgallegos/decima-human-resources/commit/80453b5b0d98c431c2f14c9a78d66890a0f98aef
